DanBot-Hosting/DanBotHostingStats

Panel/bot/discord/commands/ticket.js
ticket confirm lowercase + no awaitmessage limit
=> ticket confirm lowercase + no awaitmessage limit

Panel/bot/discord/commands/ticket.js
=> Mention channel instead sending id

Panel/bot/discord/commands/help.js
=> Updated Help To Latest

Panel/bot/discord/commands/info.js
if a bot goes to the "not in database" stage, it will share how to do, instead of just a text. Made an embed that links back to the instruction message.
=> Info has been updated with help

Panel/bot/discord/commands/ticket.js
Label command will add a label to the channel topic notifying Staff and the Requestee of the ticket status.
=> Add Label command

Panel/bot/discord/commands/eval.js
Reverts danbot-devs/DanBotHostingStats#26
=> Revert "Update eval.js"

Panel/bot/discord/commands/eval.js
Previously, I tried to make your eval command an async function. Which failed, as said here.
**Here goes take 2.**
**I better get like 4 node 7 servers after doing this :/**
=> Async Function Eval, Take 2.

createData.js
Server *Startup* tab says *Latest*, then latest :)
=> Latest Paper ;)

bot/discord/serverStatus.js
This will show memory usages for nodes in `#node-status` on discord.
=> Memory usage for nodes

bot/discord/commands/ticket/close.js
https://discord.com/channels/639477525927690240/740302560488980561/822891100670525480
=> Help out our lonely mobile users

bot/discord/commands/ping.js
This is for @NoahDevelops and @danielpmc
=> Created Ping

bot/discord/events/ready.js
Reverts DanBot-Hosting/DanBotHostingStats#69
=> Revert "Bots play with Dan"

bot/discord/events/reactionAdd.js
=> Capital letters in the DM from role react - add role

createData.js, createData_Prem.js
MongoDB does not require password if you want connect to database...
This should repair this vulnerability \_(°-°)_/
=> MongoDB not using secure instance

bot/discord/commands/staff/code.js
when you typed DBH!staff code random 3 
It would say Redeem this with DBH!server redeem random
=> fixing random

bot/discord/events/message.js, createData.js
please add memes channel and game support channel to command blacklist
=> update channel blacklist

bot/discord/commands/ticket/close.js
Its pretty simple and it works https://darks.only-fans.club/8m0L
=> This brings ticket logging and Ticket Transcript

bot/discord/commands/ticket/new.js
This pings staff when a ticket is made
=> Fixed my error!

bot/discord/commands/ticket/downgrade.js
Crete a downgrade command so if someone upgrades a ticket and then realises it can be handled by normal staff, they can downgrade it
=> Create downgrade 

bot/discord/commands/ticket/new.js
Does not ping the staff role when a new ticket has been created
=> Remove ping for staff role

bot/discord/commands/eval.js
@yuansheng1549 you forgot a () for math.random without it, it returns undefined
=> Fix the undefined for the eval

bot/discord/commands/ticket/new.js
Added a message so people will stop pinging staff all the damn time
=> Telling people to stop pinging staff when they open a ticket

bot/discord/commands/eval.js
Someone didn't have line 52 right this fixes it
=> Fixing odd thing

bot/discord/commands/ticket/downgrade.js
This fucking typo was making me go wild, thank god its being fixed by a god programmer like me. Holy god, please accept this as a good deed so i can get to heaven fast. Thanks <3
=> Fixed the worst bug ever

bot/discord/commands/ticket/remove.js
=> whoops Fix

bot/discord/commands/ticket/new.js
=> stops users from spamming new ticket

routes/me.js
maybe works, maybe doesn't who knows
=> so people cant make requests when staff apps is disabled

bot/discord/events/message.js
Name says what it does, This stops rate limits
=> Kicks a bot if they say it

bot/discord/commands/server/proxy.js
Now they will able to use proxy command with the .only-fans.club domain
=> Update Donator and booster role id for proxy command

routes/index.js
I just replaced the old discord invite that wasn’t working anymore with a new one that does works and doesn’t expire :D
=> Replacing the old discord invite with a working one

bot/discord/commands/server/create-donator.js, bot/discord/commands/server/create.js
Removed Fivem ( as Dan already announced in news ) and commented Storage because it's not ready yet and some people don't want to understand that
=> Updated server list 

bot/discord/commands/server/create.js
There was a error where it mentioned the wrong channel (which was deleted during the raid), so tiny fix.
=> Updating create.js

bot/discord/commands/ticket/add.js, bot/discord/commands/ticket/close.js, bot/discord/commands/ticket/new.js, bot/discord/commands/ticket/remove.js
For some reason the previous PR did not merge the commits, @danielpmc could you merge this PR again please.
=> Remove unnecessary styling in ticket commands - x2

bot/discord/commands/domains.js
Previous PR's files didnt get merged.
=> feat: add `domains` command to show user domains

bot/discord/commands/server/help.js
=> Fixed Typo

bot/discord/commands/staff/drop.js
This was changes to drop.js and redeem.js
=> Updating another Channel ID that doesn't exist due to the raid.

bot/discord/commands/server/create.js
Removes the help menu when the server creation is successful.
=> Hopefully removing that annoying help menu.

bot/discord/commands/server/create.js
Alright, I think I finally figured out the server creation command, this should allow DBH!server create list to show the list, while also making sure all previous changes to the create command will work like usual.
=> Resolving create command.

bot/discord/commands/stats.js
Improved readability by using a common function for all data, this makes it much more efficient and simply expandable and easier to use and understand.
=> Improved readabilty.

bot/discord/events/message.js
=> fix weird char bypass

bot/discord/commands/server/create.js
Someone reverted all these changes, so I put them back in again. DBH!server create list will now resolve without the 422 error, also removing the help menu when server creation was a success.
=> Fixing server creation command.

bot/discord/commands/server/create-donator.js, createData_Prem.js
I hope that this won’t break the bot lol
=> Add Gitea premium server creation

bot/discord/commands/server/proxy.js
I added everything you should know.
=> Added additional infos to the Proxy Command

createData.js, createData_Prem.js
imma look for other things and ghdn make this pull req ready
=> update nodejs versions

bot/discord/commands/server/delete.js
ive basically added dono-02 and dono-03 to the list of nodes that give you a premium server when deleting a server
=> adding dono-02 and dono-03, removing node 7 and node 15

bot/discord/commands/info.js
Fixed the link for info in the embed and automatically add applications.commands scope to a bot so ppl dont have to send the invite link with applications.commands scope
=> Fixed some things

bot/discord/commands/staff/premium.js
=> feat: add donator role to correct member

bot/discord/events/message.js
Bans user if message has more than 20 pings. Temporary implementation until raids stop ~~and the bot gets rewritten~~.
=> feat: implement multiple mass mention protection

bot/discord/serverUsage.js
Maybe. Maybe it does anything.
=> Maybe fixing Serverusage

bot/discord/commands/staff/code.js, bot/discord/commands/staff/drop.js
=> Cuwwys Premium Stuff

bot/discord/events/message.js
i've just removed the testing blacklisted word *that people sometimes start spamming in chat to lag the bot :/* + i've added a simple embed that is gonna be sent in the moderation log channel as soon as someone gets banned for pinging +20 people. i hope that won't break the bot lol
=> removing the testing blacklisted word + moderation log addition

routes/bot.js
I was over complicating my reasoning and somehow missed this detail. Please close my old PR as it's useless and doesn't fix the problem. This should.
=> The final solution for the user undefined error.

routes/api.js
Before, the bot didn't check if id is a number, or whether its negative, now it does.
Before, the bot didn't check if id resolves to a user and not a bot, now it does.
=> Number validation, checking if ID is a user and not a bot.

routes/api.js
forgot that data.servers is a string :sweat_smile:
=> fix to bug in previous pr

bot/discord/commands/server/count.js, bot/discord/commands/server/help.js
I have done this this morning on my phone, so check for errors before merging.
=> Create Server Count command

bot/discord/commands/staff/premiumfix.js
adding the new dono nodes (dono4) and role fixing too :) BTW i the donator nodes ids from server delete command
=> fix premiumfix command

createData.js
Disabling Node 6 server creation since the Node is down.
=> Disabling Node 6 server creation.

createData.js
Enabling Node 6 server creation again since Node seems to be stable.
=> Enabling Node 6 server creation again.

bot/discord/commands/server/create.js, bot/discord/commands/staff/premium.js, createData.js
Will be disabling Free Node creation until further notice, when Dan gets new SSDs.
Proof: https://ss.dev.dibster.live/J96zUdMPnMhv/direct https://ss.dev.dibster.live/mBOMWixqCvZY/direct
=> Completely disabling server creation on Free Nodes.

bot/discord/commands/mute.js, bot/discord/commands/snipe.js
Reverts DanBot-Hosting/DanBotHostingStats#305
=> Remove egg messages

bot/discord/events/message.js
Added staff suggestions channel ID, so messages have 👍 / 👎
=> Staff Suggestions

bot/discord/commands/stats.js
=> Fix stats command

bot/discord/commands/staff/premiumfix.js
=> feat: potential fix for premiumfix

bot/discord/events/guildMemberAdd.js
- Some formatting.
- Will no longer add role to member if it has already been kick or banned.
=> feat: updating guildMemberAdd

bot/discord/commands/staff/premium.js
The role ID isn't the proper ID.
=> feat: improper role id

bot/discord/commands/staff/premium.js
Untested changes. Should be verified by someone before merge.
=> fix: 19 digit user IDs should work.

create-free/python.js, create-premium/python.js
Updating egg to support additional and newer versions of Python.
=> feat: Python egg update

create-free/python.js, create-premium/python.js
Allowing users to use startup commands to their liking.
=> Python egg update:

bot/discord/commands/server/create.js
Just some changes to make it a bit more readable.
=> refactor(server creation): simplify code

bot/discord/commands/server/create-donator.js
Fixes it with update package errors.
=> fix: create donator server command

bot/discord/commands/staff/premium.js
The command would never give donators the proper donation role. This should now fix it.
=> fix: staff premium from not adding roles

bot/discord/commands/server/create.js
- Removing extra code.
- Checks if the server type is a valid type. If invalid, returns the server creation embed instead of a 422 error.
=> feat: update server create

bot/discord/commands/staff/maintenance.js
New command that will allow Dan to put Nodes into maintenance more easily.
hehe dan was here
=> feat: create maintenance.js

bot/discord/commands/staff/update.js
Allow Bot System Administrators to pull from GitHub manually via command.
=> feat: create staff update command

create-free/java.js, create-premium/java.js
- Updated the Java egg to support higher versions of Java.
- Allow users to select between multiple versions.
=> Java egg update.

bot/discord/commands/server/create-beta.js, bot/discord/commands/server/create-donator.js, bot/discord/commands/server/create.js, bot/discord/commands/server/docs.js, create-free/grafana.js, create-premium/grafana.js, createData.js, createData_Prem.js
- Added Grafana server creation data in `create-free` and `create-premium` directories.
- Added Grafana to server creation data files (`createData.js` & `createData_Prem.js`)
- Added Grafana to server docs command (`bot/discord/commands/server/docs.js`)
- Added Grafana to server creation commands (`bot/discord/commands/server/create.js` & `bot/discord/commands/server/create-donator.js`)
- Slight change to `bot/discord/commands/server/create-beta.js` to see if the bot will respond now.
=> feat: adding grafana egg + slight change to beta command.

bot/discord/commands/server/delete.js
=> feat(delete): allow pasting panel URLs

README.md
- Just a quick readme.md update.
=> chore: adding developers to readme

bot/discord/commands/server/list.js
- fixed codeblocks
- fixed user servers lookup
- removed repetitive code
- removed useless `setTimeout`s
- changed variables to use camelCase
- formatting cuz i cba to unstage it
=> changes to `server list` command

bot/discord/events/ready.js
=> feat: error caching

bot/discord/commands/server/create-donator.js, bot/discord/commands/server/create.js, bot/discord/commands/server/delete.js
Panel is creating ghost servers on Nodes that are down.
=> Disabling Panel Commands.

bot/discord/events/message.js
=> feat: message publishing

index.js
Yeah, we getting rid of this one today.
=> feat: removing ANOTHER useless global variable

.github/workflows/node.js.yml, .gitignore, package-lock.json
Add GitHub Workflows and remove `package-lock.json` from `.gitignore` to make the actions to work and Dependabot to make PR's. Its important to have a lock files in order to make workflows work and it will let dependabot create PR's.
The workflow will be tested on `v14`, `v16`, `v18` ofc it can be changed anytime
=> feat: add GitHub workflows

create-premium/uptimekuma.js
This will fix the donators, which if it does work, will then be merged into the free server creation, which is currently disabled.
=> Fixing the Uptime Kuma egg.

bot/discord/commands/qa.js, bot/discord/commands/tag.js
Command to have a lot of premade answers to (currently 3) common questions. 
Usage: DBH!qa <reply>
=> Answer command

bot/discord/commands/staff/premiumfix.js
Helps staff members out so they don't have to check for Dono-04 servers on panel list before.
=> fix: premium nodes updated

bot/discord/commands/server/delete.js
This commit fixes the issue where deleting a Dono-04 donator server will not accurately reflect in the user's database count.
=> fix: server deletion command

bot/discord/commands/staff/linked.js
=> chore: some changes to staff linked

bot/discord/commands/server/count.js
Server counts looks like a mess at the moment. Suggesting some simple code cleanups, removal of unused properties. 
Untested changes because we test in production like real devs. 😎
=> refactor!: cleaning up server count

bot/discord/commands/staff/proxyfix.js
Hopefully this is the fix it needs, code looked right but unsure if thats 100% correct
=> chore: Fix staff proxyfix

bot/discord/commands/server/create-donator.js, bot/discord/commands/server/redeem.js, bot/discord/commands/user/premium.js, example-config.json
Changing the node7.price to an actual variable that reflects what the variable actually does.
=> chore: changing variable name to be logical

src/commands/user/delete.js, src/util/deleteServer.js
- Allows a user to delete their panel account.
- Deletes their userData.
- Deletes their userPrem.
=> feat: Account deletion command.

src/commands/links.js, src/commands/server/docs.js
Added the docs link to the `DBH!links` command and `DBH!server docs` command
=> feat: Added Docs link

src/commands/server/list.js
Simple rewrite, removes old logic.
=> refractor!: server list command

index.js, package.json
Adding sentry logging was something that was really well done on the beta bot (thanks to @wdhdev), so I think it's only right to add it to the main bot.
=> feat: introducing sentry-logging

index.js, package.json
Reverts DanBot-Hosting/DanBotHostingStats#475
=> Revert "feat: introducing sentry-logging"

index.js
Removing unused intents that aren't needed for the bot. Someone needs to double check this.
=> chore: remove unused intents

src/commands/staff/premium.js
=> Fixed donator role assign code and some bugs

src/commands/staff/deletekey.js, src/commands/staff/drop.js
- New command to delete codes without the need of eval commands.
- QoL changes and fixes to the staff drop command.
=> feat: new helper commands

src/commands/server/unproxy.js
This should handle if the proxy is found, but the proxy location is not responding. This allows the user to be notified about it, prevent unnecessary commands from being run, and handles the error graciously.
=> fix!(unproxy): handles down servers

src/commands/server/proxy.js
Same changes made to server unproxy being applied here.
=> fix!(proxy): returning a response when timeout

src/commands/user/sync.js
This will allow users to update certain information on the bot from the panel.
=> feat: adding user sync command
